### PR TITLE
Resolve build issues and other cleanup

### PR DESCRIPTION
**Pull request by dkanada**
I don't think the MAL folder was used since that site no longer has a public API, and there was also an episode provider that was entirely commented out.

I ran into these things while I was looking into #40 and some possible solutions.

### CODE REVIEW

**Review by anthonylavado — APPROVED** [review]

**Comment by StillLoading** [comment]
Since this has not been merged yet maybe you could add "Async = true" to the XmlReaderSettings of _AniDbSeriesProvider.cs_ and _AniDbSeriesImagesProvider.cs_ . 
As it is now I get these two errors :

> Error in "AniDB"
System.InvalidOperationException: Set XmlReaderSettings.Async to true if you want to use Async Methods.
...
[ERR] "AniDbSeasonImageProvider" failed in GetImageInfos for type "Season"
System.InvalidOperationException: Set XmlReaderSettings.Async to true if you want to use Async Methods.

**Review by joshuaboniface — APPROVED** [review]

**Comment by joshuaboniface** [comment]
@StillLoading OK it's in.

**Comment by StillLoading** [comment]
Noooo, I thought @dkanada could add that async option **before** it was merged (since he was already editing those files).
But I guess we can also patch it later.

**Comment by zepx** [comment]
@StillLoading I added the Async option in #41

**Pull request merged**
