### PR TITLE
Use anisearch.com instead of .de

### PR DESCRIPTION
**Pull request by ThatNerdyPikachu**
#39

### CODE REVIEW

**Comment by Matt07211** [comment]
Why not add an option for both? So users can choose to use the English or German version

**Comment by StillLoading** [comment]
I think this should default to the library language setting shoudn't it ? 
I don't see the point in there being another place where one could change the language of the collected metadata.

**Comment by Matt07211** [comment]
Actually, I honestly never thought of that, in in favour of your idea @StillLoading

**Comment by dkanada** [comment]
I think we should make this change and also remove Proxer for now, and then implement them in a separate plugin if there is demand for a german anime metadata provider. None of these websites actually have decent support for multi-language metadata as far as I know.

**Comment by dkanada** [comment]
@joshuaboniface thoughts? I have already seen a few bug reports because of the german providers over the last few months.

**Comment by Matt07211** [comment]
That was what my suggestion when jellyfin was brand new, but every man and
his dog said if it ain't broke keep it in, and also to keep it all in a
single plugin. I was personally in favour of seperating the metadata
sources per plug-in (would also allow for an easier time implementating
support for anime lists that some of the sites do)

/salty

**Comment by dkanada** [comment]
> I think this should default to the library language setting shoudn't it?

@StillLoading this sounds like the best option to me, but it might be prudent to indicate somewhere in the plugin configuration that some providers are disabled. Maybe a select preference that defaults to `Default Language` but can also be manually changed to `English` or `German` with a description that lists the enabled providers for each language. AniSearch would use `.com` for English and `.de` for German. @ThatNerdyPikachu is this something you would be willing to add to the pull request?

**Comment by ThatNerdyPikachu** [comment]
@dkanada If I had some examples, sure. (on adding this language selection thing)

**Comment by StillLoading** [comment]
There is a "GetLibraryOptions().PreferredMetadataLanguage" call which you could "if...else...". PreferredMetadataLanguage is a property of **jellyfin/MediaBrowser.Controller/Entities/BaseItem.cs**. I'm still struggling to read C# so I'm not sure if this is the right way to do it but I hope it helps at least.

**Comment by dkanada** [comment]
I was working on what I mentioned tonight but it turns out only ImageProviders can be selectively disabled right now, so it would require server changes. The method to disable ImageProviders is kind of a hack already so I didn't want to find yet another hack for MetadataProviders.

**Comment by joshuaboniface** [comment]
#43 merged. I'm in favour of whatever works.

**Comment by joshuaboniface** [comment]
@ThatNerdyPikachu Anything else we need to do here? Looks like there's a merge conflict in the api.cs file but otherwise I think we'll be good to go with this!

**Comment by ThatNerdyPikachu** [comment]
@joshuaboniface I personally think so, yeah, we should be good. However, I wouldn't take just my opinion on it, lol.

**Comment by dkanada** [comment]
resolved in #51

**Pull request closed without merging**
