### PR TITLE
Fixed AniDB. Bumped version.

### PR DESCRIPTION
**Pull request by zepx**
This fixes AniDB by downloading the `titles.xml` correctly.

### CODE REVIEW

**Comment by dkanada** [comment]
@zepx thanks for the fix! We actually only bump the version by whole numbers for plugins though, I think netcore just requires three decimal places for versions internally. We also increment the version number [here](https://github.com/jellyfin/jellyfin-plugin-anime/blob/master/build.yaml) for the build infrastructure.

**Comment by zepx** [comment]
Thanks for the review. I've made the necessary changes.

**Review by cvium — APPROVED** [review]

**Review by Bond-009 — DISMISSED** [review]
Isn't downloading the compressed version a better idea?
Url: http://anidb.net/api/anime-titles.xml.gz
https://github.com/jellyfin/jellyfin-plugin-anime/blob/b880636e806088ba9316fa0a3f22869b42f6dd9c/Jellyfin.Plugin.Anime/Providers/AniDB/Identity/AniDbTitleDownloader.cs#L21
Ref: https://wiki.anidb.net/w/API#Anime_Titles

**Comment by oddstr13** [comment]
That may or may not do anything, depending on whether both server and http client support seamless gzip compression and decompression, but it certainly wouldn't hurt to use it explicitly.

**Comment by zepx** [comment]
As per @Bond-009 suggestion, I've switched it to using gzip explicitly. Ultimately, code changes were reverted.

**Comment by zepx** [comment]
Is this still under review? I sincerely think this ought to be merged at least for a working AniDB version. Basically, AniDB is unusable because `titles.xml` is not downloaded. By any means, if there are any necessary changes, please let me know.

Referencing @Bond-009 @joshuaboniface @cvium

**Review by joshuaboniface — APPROVED** [review]

**Comment by cvium** [comment]
Missing a version bump.

**Comment by zepx** [comment]
> Missing a version bump.

I reverted the version bump because all other pull requests did not include them. Should I be including them?

**Comment by joshuaboniface** [comment]
Yep all PRs to plugins should include a version bump both in the csproj file and build.yaml. Just increase the (first) number by 1.

**Comment by zepx** [comment]
Okay, I had it placed back in.

**Review by joshuaboniface — APPROVED** [review]

**Pull request merged**
